### ISSUE TITLE
The configurator does not save the values edited by the user in the gui

### ISSUE THREAD

**Issue by nada-dev** [mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects#33] opened 2024-02-26 19:57 UTC

**Comment by mirashanouda** [comment] 2024-02-27 09:09
Duplicate of https://github.com/mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects/issues/35

**Comment by mirashanouda** [comment] 2024-02-27 09:10
Duplicate of https://github.com/mirashanouda/AI-based-configuration-and-IDE-Java-based-tool-for-AUTOSAR-projects/issues/35

**Closed by mirashanouda** 2024-02-27 09:10 UTC
Labels: bug, duplicate, Configurator
